on:
  schedule:
  - cron: "0 5 * * *"
  push:
    branches:
      - master

name: update-relatorios

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instalar R
        uses: r-lib/actions/setup-r@v1

      - name: Instalar dependencias
        run: |
          install.packages("remotes")
          install.packages("shiny")
          remotes::install_local(".")
          remotes::install_dev("golem")
          usethis::install_dev("DBI")
          usethis::install_dev("bigrquery")
          usethis::install_dev("basedosdados")
          usethis::install_dev("dplyr")
          usethis::install_dev("stringr")
          usethis::install_dev("ggplot2")
          usethis::install_dev("scales")
          usethis::install_dev("zoo")
          usethis::install_dev("shinydashboard")
          usethis::install_dev("tibble")

        shell: Rscript {0}
      
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.TOKEN }}
      
      - name: Execute Script
        run: |
          source('data-raw/dados.R')
        shell: Rscript {0}

      - name: Conectando ao ShinyApps
        env:
          SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          shiny_token = Sys.getenv("SHINY_TOKEN")
          shiny_secret = Sys.getenv("SHINY_SECRET")
          rsconnect::setAccountInfo('fernandobastos', token = shiny_token, secret = shiny_secret)
        shell: Rscript {0}

      - name: Deploy to ShinyApps
        run: |
          rsconnect::deployApp(appTitle = "vacinacaodf", 
          forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
        shell: Rscript {0}